### ISSUE TITLE
Error when connecting snap

### ISSUE THREAD

**Issue by ayeomans** [ogra1/zoom-snap#11]
When following instructions in README.md, get error:
$ sudo snap connect zoom-client:network-manager
error: snap "zoom-client" has no plug named "network-manager"

I believe this should be 
sudo snap connect zoom-client:network-manager-observe
and documentation should be fixed.

**Comment by ogra1** [comment]
yes, the network-manager plug is gone since we have store auto-connection of all required interfaces:

https://forum.snapcraft.io/t/auto-connections-for-zoom-client/16471

i thought i had removed all references to do the manual connections in the snap store but just noticed i forgot README.md here in the tree ... 

i'll fix that ASAP, if you saw that instruction anywhere else, please tell me :)

**Comment by ayeomans** [comment]
Thanks, that's the only place I saw it.

Andrew Yeomans
