### ISSUE TITLE
Broken Tray icon in 16.04 Unity

### ISSUE THREAD

**Issue by mojibake-umd** [ogra1/zoom-snap#13]
Using Ubuntu 16.04 with Unity. 
Tray icon on the global menu bar shows a broken icon.

Let me know how I can help

**Comment by ogra1** [comment]
this is sadly something i have been trying to get fixed since day one of the snap packaging ... i tried each and every hack to make the icon show up but have not found a way to make it work in 16.04 unity7 ... it works flawless on all other desktops ... i'll definitely go on trying to get this fixed but for the moment i'm out of ideas ..

**Comment by mojibake-umd** [comment]
OK.. If just a 16.04, I was considering upgrading to 20.04 soon. 

Thank you for the reply and being on top of it. Hmmmm. I just remembered that Tusk has a tray icon, maybe something can be learned from them. Then again I think it is electron based, so that maybe a different implementation.

**Comment by mojibake-umd** [comment]
Tusk has the icon in meta/gui/ and the desktop file references that location
Icon=/snap/tusk/29/meta/gui/icon.png if that helps.
I see that the zoom-client icon is in /snap/zoom-client/75/usr/share/pixmaps/, which I understand is probably a result of the installer maybe.

**Comment by ogra1** [comment]
Snaps allow two ways to ship icons, one is snap/gui, the other is to use the upstream desktop file through a snapcraft.yaml entry and leave the rest to snapd at install time ... zoom uses the latter.
trying snap/gui was indeed one of the first things i tried ...

everything after 16.04 seems to be fine though ...

**Comment by ogra1** [comment]
With 16.04 being EOL now i'm closing this issue...
