### ISSUE TITLE
Sound drops every time someone joins a zoom meeting I'm hosting

### ISSUE THREAD

**Issue by quilicicf** [ogra1/zoom-snap#17]
Hi, 

Every time someone joins a zoom meeting I'm hosting, my sound (output) drops down so much I can't hear anything. 

I can still hear them if I boost the sound on my OS but then I get heart attacks when I resume my music or receive a notification. 

My OS is Ubuntu 18.04 and zoom version: `3.5.392530.0421`. 

I have to leave/re-join every time to avoid boosting the sound to crazy levels.

Thanks,

> EDIT: the output volume in sound settings was set to 50%. Setting it to 100% fixed this issue. You can always try that.

**Comment by ogra1** [comment]
have you tried adjusting the levels inside the app settings (there are extra sliders in the audio tab)

**Comment by quilicicf** [comment]
I don't see any sliders.

The issue only appears during a call. 

When I'm in a call I can only access the audio settings from the `Arrow Up` next to the microphone icon and there's no sliders there.

**Comment by quilicicf** [comment]
Should I try to adjust the sliders when my call ends (I'm in the middle of a call right now) and see if it fixes something?

**Comment by quilicicf** [comment]
Seems to work Oo

To anyone having this issue, I had the output sound volume set to half of maximum, when it's at maximum the bug disappears. 

:shrug:

**Comment by ogra1** [comment]
I was asking you to check the in-app settings because I noticed too that they are seemingly using a slider implementation that works linear instead of logarithmic, but thats a zoom issue I can not really do anything about on the packaging side ... using a linear volume control means it feels like it does nothing until half volume and feels super-sensitive for the rest of the way.

**Comment by quilicicf** [comment]
Let's close this then, thanks for the tip anyway :+1:
