### ISSUE TITLE
Snap audio permission has no effect

### ISSUE THREAD

**Issue by skumblex** [ogra1/zoom-snap#23]
System: KDE Neon User Edition 5.18 based in Ubuntu 18.04
Zoom version: 5.0.399860.0429 2020-05-01

When I uncheck the permission '**Play and record sound**', the Zoom client is still able to play and record audio. The camera permission on the other hand works just fine. For reference, I also tested the audacity snap, but in this case, the audio permission works as intended. So I assume this is some problem with the packaging?

![image](https://user-images.githubusercontent.com/47532112/81602954-cf141500-93cd-11ea-9e4a-42387fdc63e6.png)

**Comment by ogra1** [comment]
this is a shirtcoming in the KDE UI i fear ... the "Play and record sound" is the pulseaudio plug that is normally not connected ... i had to add it for older systems in https://github.com/ogra1/zoom-snap/issues/3 where the new separate "audio-record" and "audio-playback" interfaces did not exist ... 

the KDE UI does not seem up to date with the interfaces it can show, this is how it should look like:

![Bildschirmfoto von 2020-05-11 23-06-38](https://user-images.githubusercontent.com/15386365/81612079-81eb6f80-93dc-11ea-8a30-0ef3afdf8a97.png)

you should be able to manage the connections from a terminal using:
```
snap connections zoom-client
```
and to disable audio recording:
```
sudo snap disconnect zoom-client:audio-record
```
equivalently for any other interface ... to connect them again you can use ```sudo snap connect ...```

**Comment by skumblex** [comment]
Great, thanks!

I can confirm that this is indeed a visualization issue. I was using the 'Snap Store' snap to manage permissions, which apparently does not show all the available connections.

**Comment by ogra1** [comment]
my screenshot is from the snap-store snap too. 
are you tracking the correct channel of the snap-store ?
the final release has switched it to:
```
snap info snap-store|grep tracking
tracking:     latest/stable/ubuntu-20.04
```
if you are on a different channel, try:
```
sudo snap refresh --channel=latest/stable/ubuntu-20.04 snap-store
```

that should hopefully give you the same UI i have ...

**Comment by skumblex** [comment]
Interesting,
this was indeed the problem. Since KDE Neon is still on 18.04, I had the 18.04 version of the snap store, which seems to be different from the 20.04 version. So apparently _latest/stable/ubuntu-20.04_ and _latest/stable/ubuntu-18.04_ are different versions of the app.

**Comment by pabloab** [comment]
[Same issue](https://i.stack.imgur.com/BvdYh.png) with GNOME 3.28.4 and "gnome-software-plugin-snap   3.28.1-0ubuntu4.18.04.15" (snap-store is not installed). Although being a "visualization issue" seems a severe security one. Users should be able to rely that permission they allow on the GUI faithfully reflect backend.

Considering this affects KDE also I'm not sure where should I file the bug.

**Comment by ogra1** [comment]
> Considering this affects KDE also I'm not sure where should I file the bug. On [snappy](https://bugs.launchpad.net/snappy/)? (AKA [snapd](https://github.com/snapcore/snapd)?)
> 
essentially you should file it against the snap store (https://bugs.launchpad.net/snap-store/)
the code is identical and maintaed by the same team ... i'd have liked to leave out the pulseaudio interface completely (in fact in the beginning i did) but that would have made it not work for quite a few people on distros where snapd has not been updated in a while (see: https://github.com/ogra1/zoom-snap/issues/3 )

> Also, AFAIK this [shouldn't be enabled/connected by default](https://snapcraft.io/docs/audio-record-interface), and it is. Both problems look like snapd security issues.

this is connected on purpose, normally you wouold leave this to the user, you are right, but zoom is written in a way that it immediately crashes with no notice if no recording source is found. since i have no influence on how zoom works (it is proprietary after all) the only way to fix this is pre-connecting such interfaces, there is an explicit process for such a case where the snap gets a review from the security team before auto-connection is granted:

https://forum.snapcraft.io/t/auto-connections-for-zoom-client/16471
