### ISSUE TITLE
can't type into meeting ID field

### ISSUE THREAD

**Issue by brainwane** [ogra1/zoom-snap#47]
Using version 5.2.454870.0831, on Debian buster, as of yesterday:

When I launch the Zoom client, when I select the "enter meeting ID field or personal link name" field, I cannot type into it or paste into it. Thus I cannot join a meeting at all.

(I am also using [this workaround](https://github.com/ogra1/zoom-snap/issues/31#issuecomment-669321318) to deal with fonts.)

**Comment by ogra1** [comment]
Hmm, you should (since at least ten revisions of the snap) not have to do anything for font support anymore, it would be helpful if you could open a new issue for this with an exact description what did not work for you ...

regarding the input field, i can not reproduce this here (on ubuntu 16.40 and 20.04), are you using wayland by chance ?

also there was a fresh release two days ago, please refresh to this first and try again:

    sudo snap refresh zoom-client

should get you onto 5.2.458699.0906

**Comment by brainwane** [comment]
Yes, I'm using Wayland. I think #31 is the issue I had.

I did the `sudo snap refresh zoom-client` and ran the updated client, and the problem still occurred, but then I:

* rebooted my machine, which had been up for probably ~12 days
* did an apt update which showed me that a few upgrades were available, and performed them:

~~~
libzmq5/stable,stable 4.3.1-4+deb10u2 amd64 [upgradable from: 4.3.1-4+deb10u1]
xserver-common/stable,stable 2:1.20.4-1+deb10u1 all [upgradable from: 2:1.20.4-1]
xserver-xephyr/stable,stable 2:1.20.4-1+deb10u1 amd64 [upgradable from: 2:1.20.4-1]
xserver-xorg-core/stable,stable 2:1.20.4-1+deb10u1 amd64 [upgradable from: 2:1.20.4-1]
xserver-xorg-legacy/stable,stable 2:1.20.4-1+deb10u1 amd64 [upgradable from: 2:1.20.4-1]
xwayland/stable,stable 2:1.20.4-1+deb10u1 amd64 [upgradable from: 2:1.20.4-1]
~~~

and now the problem is resolved! I'm closing this issue but of course feel free to reopen it if you want to pursue a deeper explanation.
