### ISSUE TITLE
Zoom app in ubantu gives me errors

### ISSUE THREAD

**Issue by SyedShahmirKazmi** [ogra1/zoom-snap#6]
it opened once ,it stucked and now on clicking several times it isn't responding

**Comment by ogra1** [comment]
did you connect all the needed interfaces ? the hang typically happens if the audio-record interface was not connected ... 

see the text of https://snapcraft.io/zoom-client ...
```
sudo snap connect zoom-client:audio-record
sudo snap connect zoom-client:camera
sudo snap connect zoom-client:hardware-observe
sudo snap connect zoom-client:network-manager
sudo snap connect zoom-client:system-observe
```
or if you prefer using the UI, see the second screenshot:

https://dashboard.snapcraft.io/site_media/appmedia/2020/03/zoom-perm.png

does it work if you connect all the interfaces ?

**Comment by ogra1** [comment]
an auto-connection request has been filed at:
https://forum.snapcraft.io/t/auto-connections-for-zoom-client/16471

once this is fully approved no manaul connections should be necessary anymore.

**Comment by Nileshunique** [comment]
audio is not working in ubuntu  even 
    sudo snap connect zoom-client:audio-record
    sudo snap connect zoom-client:camera
    sudo snap connect zoom-client:hardware-observe
    sudo snap connect zoom-client:network-manager
    sudo snap connect zoom-client:system-observe
all these configuration has to be done.

**Comment by SyedShahmirKazmi** [comment]
i went to ubantu software repositories and searched zoom ,it showed installed , a permission tab was under it , from there i allowed all permission and now it works fine
