### ISSUE TITLE
snap is not installable on Solus

### ISSUE THREAD

**Issue by kirienko** [ogra1/zoom-snap#74]
I'm trying to install zoom on Solus with snap. It used to work before, but now I see:
```
$ sudo snap install zoom-client
error: cannot perform the following tasks:
- Mount snap "zoom-client" (134) (exit status 1)
```
For the `--beta` I've got the following:
```
$ sudo snap install --beta zoom-client 
2021-02-23T20:24:21+01:00 INFO snap "zoom-client" has bad plugs or slots: audio-playback (unknown interface "audio-playback"); audio-record (unknown interface
"audio-record")
error: cannot perform the following tasks:
- Run configure hook of "zoom-client" snap if present (run hook "configure": free(): double free detected in tcache 2)
```
And it is the same with the downloaded package:
```
$ sudo snap install ./zoom-client_134.snap 
error: cannot install snap file: exit status 1
```

It was the only convenient way to install Zoom on Solus. At the moment there's no any :-(

**Comment by ogra1** [comment]
this looks like a more general snap problem, can you install any other snaps (try ```htop``` that's small and fast to install) ?
also your snapd seems really old if it does not know about the audio-playback interface, what is the full output of ```snap version```

**Comment by kirienko** [comment]
The version is this:
```
$ snap version 
snap    2.39.3
snapd   2.39.3
series  16
solus   4.2
kernel  5.10.15-172.current
```
You're right, I tried to install `htop` and it failed with the same error as above. I don't know if it is related to the fact that I have `htop` installed already?

I also tried to install something that I didn't have before: `sudo snap install tmux --classic`. And it does work. Although it requires `--classic`, otherwise it doesn't.

**Comment by ogra1** [comment]
> You're right, I tried to install `htop` and it failed with the same error as above. I don't know if it is related to the fact that I have `htop` installed already?
...
> I also tried to install something that I didn't have before: `sudo snap install tmux --classic`. And it does work. Although it requires `--classic`, otherwise it doesn't.

it looks like your system is not able to install strict snaps then (which is rather the majority, classic snaps like tmux are rare). htop from your distros package manager will happily work with a snapped htop installed alongside, this is not an issue. 

snapd 2.39 is really old, the current one is 2.48.2.1, you should contact the solus developers or create a topic at https://forum.snapcraft.io/ (you can include "snap version" output, the actual error you see, the output of "snap changes" and if you run "jounralctl -f" in a second terminal while trying to install a snap, paste also the lines that are printed there)

since this does not seem to be zoom related at all but rather a bug with how your distro handles snaps, i'm closing this issue

**Comment by kirienko** [comment]
Thanks for the explanation, I'll try to follow the way you've described.
