### ISSUE TITLE
In edge channel (148) Decorations dont follow yaru/theme

### ISSUE THREAD

**Issue by edurojasr** [ogra1/zoom-snap#77]
HI!

In the edge channel (148) I noticed  that the window theme does not match with the yaru theme. Before it did!

![image](https://user-images.githubusercontent.com/35645729/119738481-05d49600-be3e-11eb-86d7-d35ceed9a58e.png)
 Yaru theme decorator in firefox.

![image](https://user-images.githubusercontent.com/35645729/119738533-14bb4880-be3e-11eb-9400-04d2fcb0b858.png)
unkown theme decorator in zoom-client (148)

**Comment by ogra1** [comment]
hmm, i do not see this on 20.04 (x11) here ... probably they moved to client-side-decorations when used in wayland ...

**Comment by edurojasr** [comment]
Yes I can confirm that in X11 Ubuntu 21.04 decorations match with Yaru.

But it seems to me that before 148 in Wayland the zoom-client Snap did fallow the yaru theme... Or am I wrong?

**Comment by ogra1** [comment]
if there was any change it was not in the packaging. 
148 is an automatically triggered package build because the zoom deb got updated by zoom ... i did not notice different decorations when testing the screen sharing with 147, but i also did not pay attention to that particular detail :) (and i run xorg on a day to day basis here)

**Comment by edurojasr** [comment]
Ok thanks @ogra1!

I Try to do a revert just for test, but it's not possible.

But it's what it is! So I'm ok

You can close this since it's not an issue.

Thanks
